# Generated by Django 3.2.8 on 2021-11-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='down_vote',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
