# Generated by Django 3.2.8 on 2021-11-10 07:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fapp', '0003_auto_20211109_1814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Up_Vote',
            new_name='UpVote',
        ),
    ]
