# Generated by Django 3.2.8 on 2021-11-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0005_downvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='down_vote',
        ),
    ]
