name: Foodie Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SECRET_KEY: reallyfakesecretpalls
      SENDGRID_API_KEY: fakerandomapikey
      EMAIL_HOST: smtp.sendgrid.net
      EMAIL_USE_TLS: True
      EMAIL_PORT: 587
      FROM_EMAIL: kamolunehemiah@gmail.com
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
